# Generated by Django 4.2.7 on 2023-11-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_timestamp_applyjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='company',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
