# Generated by Django 4.2.7 on 2023-12-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_industry_state_job_job_type_job_industry_job_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='city',
        ),
    ]
